- hosts: test-server
  become: yes
  tasks:
    - name: install wget
      yum: name=wget state=present

    - name: download epel - httpd24.repo
      command: wget https://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo -P /etc/yum.repos.d

    - name: install httpd24
      yum: name=httpd24 state=present

    - name: install epel-release
      yum: name=epel-release state=present

    - name: install remi
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present

    - name: install php56
      yum: name=php56 state=present

    - name: install mysql-community-release-el6-5.noarch.rpm
      yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

    - name: install epel for mysql
      yum: name=http://dl.iuscommunity.org/pub/ius/stable/Redhat/6/x86_64/ius-release-1.0-14.ius.el6.noarch.rpm state=present

    - name: install epel for mysql
      yum: name=http://dl.iuscommunity.org/pub/ius/stable/Redhat/6/x86_64/epel-release-6-5.noarch.rpm state=present

    - name: is mysql55-server already installed
      shell: rpm -qa | grep mysql55-server
      register: already_mysql
      failed_when: already_mysql not in [0, 1]

    - name: remove mysql 
      yum: name=mysql state=absent
      when: already_mysql.rc == 1

    - name: install mysql55-server
      yum: name=mysql55-server state=present

    - name: install 
      yum: name=ftp://195.220.108.108/linux/remi/enterprise/6/remi/x86_64/php56-mysqlnd-qc-panel-1.2.0-6.el6.remi.noarch.rpm state=present

    - name: install php56u-mysqlnd
      yum: name=php56u-mysqlnd state=present

