- hosts: test-server
  tasks:
    - name: install wget
      become: yes
      yum: name=wget state=present

    - name: check epel-httpd24.repo
      stat: path=/etc/yum.repos.d/epel-httpd24.repo
      register: is_file

    - name: download epel - httpd24.repo
      become: yes
      command: wget https://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo -P /etc/yum.repos.d
      when: not is_file.stat.exists

    - name: install httpd24
      become: yes
      yum: name=httpd24 state=present

    - name: install remi
      become: yes
      yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present

    - name: install php56
      become: yes
      yum: name=php56 state=present

    - name: is mysql55-server already installed
      shell: rpm -qa | grep mysql55-server
      register: already_mysql
      failed_when: already_mysql.rc not in [0, 1]

    - name: remove mysql-libs
      become: yes
      yum: name=mysql-libs state=absent
      when: already_mysql.rc == 1

    - name: install mysql-community-release-el6-5.noarch.rpm
      become: yes
      yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

    - name: install epel for mysql
      become: yes
      yum: name=http://dl.iuscommunity.org/pub/ius/stable/Redhat/6/x86_64/ius-release-1.0-14.ius.el6.noarch.rpm state=present

    - name: install mysql55-server
      become: yes
      yum: name=mysql55-server state=present

    - name: install php56u-mysqlnd
      become: yes
      yum: name=php56u-mysqlnd state=present

