---
- name: check epel-httpd24.repo
  stat: path=/etc/yum.repos.d/epel-httpd24.repo
  register: is_file

- name: download epel - httpd24.repo
  command: wget https://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo -P /etc/yum.repos.d
  when: not is_file.stat.exists

- name: install httpd24
  yum: name=httpd24 state=present

- name: start httpd
  service: name=httpd state=started enabled=yes

- name: groupadd www
  group: name=www state=present

- name: usermod -a -G www vagrant
  user: name=vagrant groups=www append=yes

- name: ln -s /var/www /opt/rh/httpd24/root/var/www
  file: path=/var/www src=/opt/rh/httpd24/root/var/www state=link group=www

- name: chown -R root:www /opt/rh/httpd24/root/var/www
  file: path=/opt/rh/httpd24/root/var/www group=www mode=2775

- name: get dir permission list
  shell: find /opt/rh/httpd24/root/var/www -type d | xargs ls -ld | awk '{print $1;}'
  register: dir_permission_list
  changed_when: false
  always_run: yes

- name: find /var/www -type d -exec sudo chmod 2775 {} \;
  shell: find /opt/rh/httpd24/root/var/www -type d -exec sudo chmod 2775 {} \;
  when: dir_permission_list.stdout_lines.count("d") > dir_permission_list.stdout_lines.count("drwxrwsr-x")
