---
- name: check epel-httpd24.repo
  stat: path=/etc/yum.repos.d/epel-httpd24.repo
  register: is_file

- name: download epel - httpd24.repo
  command: wget https://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo -P /etc/yum.repos.d
  when: not is_file.stat.exists

- name: install httpd24
  yum: name=httpd24 state=present

- name: start httpd
  service: name=httpd state=started enabled=yes

- name: groupadd www
  group: name=www state=present

- name: usermod -a -G www vagrant
  user: name=vagrant groups=www append=yes

- name: ln -s /var/www /opt/rh/httpd24/root/var/www
  file: path=/var/www src=/opt/rh/httpd24/root/var/www state=link group=www

- name: get www dir list
  command: find /opt/rh/httpd24/root/var/www -type d
  register: list_dir_www
  changed_when: false
  always_run: yes
  tags:
    - test

- name: chown -R root:www /opt/rh/httpd24/root/var/www
  file: path="{{item}}" group=www mode=2775
  with_items: list_dir_www['stdout_lines']
  tags:
    - test

- name: get www file list
  command: find /opt/rh/httpd24/root/var/www -type f
  register: list_file_www
  changed_when: false
  always_run: yes
  tags:
    - test

- name: chmod 0664 -R /opt/rh/httpd24/root/var/www
  file: path='{{item}}' group=www mode=0664
  with_items: list_file_www.stdout_lines
  tags:
    - test
