---
- name: sudo um install http://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-14.ius.centos6.noarch.rpm
  yum: name=http://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-14.ius.centos6.noarch.rpm state=present

- name: sudo yum install httpd24u
  yum: name=httpd24u state=present

- name: sudo service httpd start
  service: name=httpd state=started enabled=yes

- name: sudo groupadd www
  group: name=www state=present

- name: sudo usermod -a -G www vagrant
  user: name=vagrant groups=www append=yes

- name: get www dir list
  command: find /var/www -type d
  register: list_dir_www
  changed_when: false
  always_run: yes

- name: sudo chown -R root:www /var/www
  file: path="{{ item }}" group=www mode=2775
  with_items: "{{ list_dir_www['stdout_lines'] }}"

- name: get www file list
  command: find /var/www -type f
  register: list_file_www
  changed_when: false
  always_run: yes

- name: chmod 0664 -R /var/www
  file: path="{{ item }}" group=www mode=0664
  with_items: "{{ list_file_www['stdout_lines'] }}"

- name: grep "index.php" /etc/httpd/conf/httpd.conf
  command: grep "index.php" /etc/httpd/conf/httpd.conf
  register: grep_httpd_conf
  failed_when: grep_httpd_conf.rc not in [0, 1]
  changed_when: false
  always_run: yes

- name: cp templates/httpd/httpd.conf /etc/httpd/conf/httpd.conf
  copy: >
    src="templates/httpd/httpd.conf"
    dest="/etc/httpd/conf/httpd.conf"
    force=yes
    backup=yes
  notify:
    - restart httpd
  when: grep_httpd_conf.rc == 1
