---
- name: check epel-httpd24.repo
  stat: path=/etc/yum.repos.d/epel-httpd24.repo
  register: is_file

- name: download epel - httpd24.repo
  command: wget https://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo -P /etc/yum.repos.d
  when: not is_file.stat.exists

- name: install httpd24
  yum: name=httpd24 state=present

- name: groupadd www
  group: name=www state=present
  tags: 
    - user

- name: usermod -a -G www vagrant
  user: name=vagrant groups=www append=yes
  tags: 
    - user

- name: ln -s /var/www /opt/rh/httpd24/root/var/www
  file: path=/var/www src=/opt/rh/httpd24/root/var/www state=link
  tags:
    - user 
