---
- name: rpm -qa | grep mysql55-server
  shell: rpm -qa | grep mysql55-server
  register: grep_mysql55_server
  failed_when: grep_mysql55_server.rc not in [0, 1]
  changed_when: false
  always_run: yes

- name: remove mysql-libs
  yum: name=mysql-libs state=absent
  when: grep_mysql55_server.rc == 1

- name: install mysql-community-release-el6-5.noarch.rpm
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

- name: install epel for mysql
  yum: name=http://dl.iuscommunity.org/pub/ius/stable/Redhat/6/x86_64/ius-release-1.0-14.ius.el6.noarch.rpm state=present

- name: install mysql55-server
  yum: name=mysql55-server state=present

- name: service mysqld start
  service: name=mysqld state=started enabled=yes 
