---
- name: rpm -qa | grep mysql55-server
  shell: rpm -qa | grep mysql55-server
  register: grep_mysql55_server
  failed_when: grep_mysql55_server.rc not in [0, 1]
  changed_when: false
  always_run: yes

- name: remove mysql-libs
  yum: name=mysql-libs state=absent
  when: grep_mysql55_server.rc == 1

- name: install mysql-community-release-el6-5.noarch.rpm
  yum: name=http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm state=present

- name: install epel for mysql
  yum: name=http://dl.iuscommunity.org/pub/ius/stable/Redhat/6/x86_64/ius-release-1.0-14.ius.el6.noarch.rpm state=present

- name: install mysql55-server
  yum: name=mysql55-server state=present

- name: service mysqld start
  service: name=mysqld state=started enabled=yes

- name: check file mysql
  stat: path=/etc/my.conf.d/login.cnf
  register: is_mysql_login_conf
  changed_when: false
  always_run: yes
  tags:
    - test

- name: Create root user password
  shell: cat /dev/urandom | LC_CTYPE=C tr -dc '[:alnum:]' | head -c 16
  register: mysql_root_password
  when: not is_mysql_login_conf.stat.exists
  tags:
    - test

- name: Execute mysql_secure_installation
  script: roles/lamp/sh/secure_install.sh {{ mysql_root_password.stdout | quote }}
  register: mysql_secure_installation
  when: not is_mysql_login_conf.stat.exists
  tags:
    - test

- name: Add Line for include append config
  lineinfile: >
    dest=/etc/my.cnf
    line="!includedir /etc/my.cnf.d"
    backup=yes
  when: not is_mysql_login_conf.stat.exists
  tags:
    - test

- name: mkdir my.cnf.d
  file: >
    path=/etc/my.conf.d
    state=directory
    owner=root
    group=root
    mode=0755

- name: cp my.cnf /etc/my.cnf.d/login.cnf
  template: >
    src=my.cnf.j2
    dest=/etc/my.cnf.d/login.cnf
    owner=root
    group=root
    mode=0600
  notify:
    - restart mysqld
  when: not is_mysql_login_conf.stat.exists
  tags:
    - test
