---

- name: yum install php-fpm
  yum: name=php-fpm state=present
  tags:
    - test

#- name: install remi
#  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present

#- name: install php56
#  yum: name=php56 state=present

