---

- name: sudo yum install remi
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present

- name: sudo yum install php-fpm php-pdo php-mysqlnd ...
  yum: name={{ item }} state=present enablerepo=remi,remi-php56
  with_items:
    - php-fpm
    - php-pdo
    - php-mysqlnd
    - php-opcache
    - php-devel
    - php-mbstring
    - php-mcrypt
    - php-mysql
    - php-phpunit-PHPUnit
    - php-pecl-xdebug
    - php-cli
    - php-common
    - gd-last
    - php-gd
    - ImageMagick-last
    - phpMyAdmin

- name: sudo service php-fpm start
  service: name=php-fpm state=started enabled=yes

- name: cp httpd/php.conf /etc/httpd/conf.d/php.conf
  copy: src="httpd/php.conf" dest="/etc/httpd/conf.d/php.conf"
  notify:
    - restart httpd

- name: grep "# Apache 2.2" /etc/httpd/conf.d/phpMyAdmin.conf
  command: grep "# Apache 2.2" /etc/httpd/conf.d/phpMyAdmin.conf
  register: grep_phpMyAdmin_conf
  failed_when: grep_phpMyAdmin_conf.rc not in [0, 1]
  changed_when: false
  always_run: yes

- name: cp httpd/phpMyAdmin.conf /etc/httpd/conf.d/phpMyAdmin.conf
  copy: >
    src="httpd/phpMyAdmin.conf"
    dest="/etc/httpd/conf.d/phpMyAdmin.conf"
    force=yes
    backup=yes
  notify:
    - restart httpd
  when: grep_phpMyAdmin_conf.rc == 0
